// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return android;
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcvnhQ_k7LVAZgTr8BGenuiQIf-UUmUYo',
    appId: '1:118109385726:android:b37bc545d8d13762c586af',
    messagingSenderId: '118109385726',
    projectId: 'neurotracer-walt',
    databaseURL: 'https://neurotracer-walt-default-rtdb.firebaseio.com',
    storageBucket: 'neurotracer-walt.firebasestorage.app',
  );
}
